### PR TITLE
SetColor() instead of AddColor(), made sure that a call to Render() always renders

### PR DESCRIPTION
**Pull request by DelSystem32**
Now using MaterialPropertyBlock.SetColor() instead of
MaterialPropertyBlock.AddColor(), which had been deprecated in Unity.

Removed "private bool needsUpdate;" in "lwf_uivertex_factory.cs" and
"lwf_combinedmesh_factory.cs" because a call to Render() should always
guarantee to render the flash. Things can be repositioned etc via custom
code outside of Update() in "lwf_core.cs" and these changes need to be
reflected when calling Render() in "lwf_core.cs".

I made this fork because of https://github.com/gree/lwf/issues/156

A call to Render() *needs* to always render because you can manipulate MovieClips from outside LWF (for example change their x property and so forth).

### CODE REVIEW

**Comment by KojiNakamaru** [comment]
Thank you for the pull request. In #156 you noted
> When lwf.updateCount is 0 the needsUpdate boolean never becomes true in "lwf_uivertex_factory.cs" or "lwf_combinedmesh_factory.cs".
but updateCount is initialized as -1 so needsUpdate should become true immediately. I introduced needsUpdate in https://github.com/gree/lwf/pull/153 not for performance optimization but for the rendering correctness. Maybe I miss something, so could you please provide a simple fla file that reproduces the issue? I'll then track the issue.

**Comment by KojiNakamaru** [comment]
Okay, I found the real cause in LWFObject.cs:
https://github.com/gree/lwf/blob/dcf64937400dab0cd599a4f38f88c9e7b792d643/csharp/unity/wrapper/LWFObject.cs#L354-L359
If we remove this part, the code with needsUpdate works.

I would like to merge your pull request except parts about needsUpdate and to fix LWFObject. Is it okay for you?

**Comment by KojiNakamaru** [comment]
As discussed above, I've fixed LWFObject in https://github.com/gree/lwf/pull/160, merged your https://github.com/gree/lwf/pull/158, and reverted changes about needsUpdate in https://github.com/gree/lwf/pull/161. Could you please try the latest repository.

BTW, about the following,

> A call to Render() needs to always render because you can manipulate MovieClips from outside LWF (for example change their x property and so forth).

even the implementation before https://github.com/gree/lwf/pull/153 waits until lwf.updateCount is updated, thus always keeps the fps. If you needs to reflect your change immediately, you could choose one of the following:

* Simply use a high fps setting (such as 30 or more)
* Define another custom renderer that also looks lwf.needsUpdate.

**Comment by DelSystem32** [comment]
Seems like everything is working like it should now, thank you for your hard work!

**Pull request merged**
